### ISSUE TITLE
If there is no license to code is not under copyright laws.

### ISSUE THREAD

**Issue by et-sollertis-animi** [cuboiddiscord/cuboiddiscord.github.io#1]
Github is open-source. If you don't want to make it open, then make the repo private.

**Comment by 7-Abdul** [comment]
Well its part of the github laws. There is a picture, lemme show you

**Comment by 7-Abdul** [comment]
Github Says in their terms of service:
"If you want others to use, distribute, modify, or contribute back to your project, you need to include an open-source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it's public, unless you explicitly give them the right to do so."

**Comment by et-sollertis-animi** [comment]
> Github Says in their terms of service:
> "If you want others to use, distribute, modify, or contribute back to your project, you need to include an open-source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it's public unless you explicitly give them the right to do so."

It says "for example." That means that you can use a license that does that for you.

**Comment by abduldoesdev** [comment]
> u

Oh OK, that works too. I am not fully familiar with licenses, but I will make one soon. Thanks!

**Comment by et-sollertis-animi** [comment]
> Oh OK, that works too. I am not fully familiar with licenses, but I will make one soon. Thanks!

You can't make one, you have to get one off the Github database

**Comment by abduldoesdev** [comment]
> > Oh OK, that works too. I am not fully familiar with licenses, but I will make one soon. Thanks!
> 
> You can't make one, you have to get one off the Github database

Umm ok then. lol
